gcc: aarch64: arm_acle.h: Fix compile error on GCC-9
There's a lonely induce in upstream GCC-9(since 9.4.0), which would cause
compile error:
error: template with C linkage

Change-Id: I35b9c0d1291e82a7d291b7e0f38278e38710e2b0
Signed-off-by: Jeffy Chen <jeffy.chen@rock-chips.com>