Revert "package: mpg123: update new version to fix the noise of playback mp3"
Fix the compiler error on RK3568 32-bit:

3568_32/build/mpg123-1.28.0/src/libout123/.libs -Wl,-rpath -Wl,/home/wxt/linux-develop/rk356x/buildroot/output/rockchip_rk3568_32/build/mpg123-1.28.0/src/libsyn123/.libs -Wl,-rpath -Wl,/home/wxt/linux-develop/rk356x/buildroot/output/rockchip_rk3568_32/host/arm-buildroot-linux-gnueabihf/sysroot/usr/lib -Wl,-rpath -Wl,/home/wxt/linux-develop/rk356x/buildroot/output/rockchip_rk3568_32/host/arm-buildroot-linux-gnueabihf/sysroot/usr/lib
2021-07-18T23:56:19 src/libmpg123/.libs/libmpg123.so: undefined reference to `INT123_synth_1to1_s32_neon_asm'
2021-07-18T23:56:19 src/libmpg123/.libs/libmpg123.so: undefined reference to `INT123_synth_1to1_s32_s_neon_asm'
2021-07-18T23:56:19 src/libmpg123/.libs/libmpg123.so: undefined reference to `INT123_dct36_neon'
2021-07-18T23:56:19 src/libmpg123/.libs/libmpg123.so: undefined reference to `INT123_synth_1to1_s_neon_accurate_asm'
2021-07-18T23:56:19 src/libmpg123/.libs/libmpg123.so: undefined reference to `INT123_synth_1to1_real_neon_asm'
2021-07-18T23:56:19 src/libmpg123/.libs/libmpg123.so: undefined reference to `INT123_synth_1to1_neon_accurate_asm'
2021-07-18T23:56:19 src/libmpg123/.libs/libmpg123.so: undefined reference to `INT123_dither_table_init'
2021-07-18T23:56:19 src/libmpg123/.libs/libmpg123.so: undefined reference to `INT123_dct64_real_neon'
2021-07-18T23:56:19 src/libmpg123/.libs/libmpg123.so: undefined reference to `INT123_synth_1to1_real_s_neon_asm'
2021-07-18T23:56:19 collect2: error: ld returned 1 exit status
2021-07-18T23:56:19 Makefile:3692: recipe for target 'src/mpg123' failed
2021-07-18T23:56:19 make[2]: *** [src/mpg123] Error 1

This reverts commit b7f4ada38d262ed3e499ee390462bb2c5089475c.

Change-Id: I668d93aa98421b64354e741b6128eadbe14c664a
Signed-off-by: Xing Zheng <zhengxing@rock-chips.com>